#!/usr/bin/env/R
####### ACSN enrichment analysis ####### 

#' @title Enrichment analysis function
#' @description Allows gene set enrichment analysis
#' @param Genes Character vector of genes that should be tested for enrichment
#' @param maps list of maps generated by format_from_gmt. Default: tests on all acsn maps
#' @param correction_multitest either FALSE, "Bonferroni", "BH", or "FDR"
#' @param statistical test one of "fisher", "hypergeom"
#' @param min_module_size will remove from the analysis all modules which are (strictly) smaller than threshold
#' @param universe Universe on which the statistical analysis should be performed. Can be either "HUGO","ACSN", or a character vector of genes.
enrichment<-function(Genes=NULL,
                    maps = list(ACSN_apop_formatted,
                                ACSN_cellcyc_formatted,
                                ACSN_dnarep_formatted,
                                ACSN_emtmotil_formatted,
                                ACSN_master_formatted,
                                ACSN_survival_formatted), 
                    correction_multitest = FALSE,
                    statistical_test = "fisher",
                    min_module_size = 5,
                    universe = "HUGO"){
  
  ### Checking that gene list is unique
  Genes<-unique(Genes)
  Genes_size<-length(Genes)    
  
  
  if(universe == "HUGO"){
    ###Total size of approved symbols, from http://www.genenames.org/cgi-bin/statistics, as of October 8th 2015
    size = 39480
  }
  
  else if(universe == "ACSN"){
    genesACSN<-character()
    iterator<-0
    for(lt in maps){
      iterator<-iterator+1
      ### extract modules of size >= module_size and get size of ACSN reduced by module size
      result<-data.frame()
      for(k in 1:dim(lt)[1]){
        spare_genes<-as.character(lt[k,-c(1,2)])
        S<-sum(spare_genes != "")
        if( S>= min_module_size){
          genesACSN<-unique(c(genesACSN,unique(spare_genes[spare_genes!=""])))
          result<-rbind(result,cbind(lt[k,1],S,t(spare_genes)))          
        }
      }
      size <- length(genesACSN)
      maps[[iterator]]<-result
    }
    is_in_ACSN<-Genes %in% genesACSN
    S<-sum(!is_in_ACSN)
    if(S > 0){ ### removing genes from list, that are not from ACSN
      warning(paste(S,"genes are not in ACSN modules and will be excluded from analysis"))
    }
    Genes<-Genes[is_in_ACSN]
    
  }
  else if(is.character(universe)){
    
    ### Change maps so that they only have gene names from universe and remove modules which are too small
    genesACSN<-character()
    i<-0
    genesACSN<-character()
    iterator<-0
    for(lt in maps){
      iterator<-iterator+1
      ### extract modules of size >= module_size and get size of ACSN reduced by universe and module size
      result<-data.frame()
      for(k in 1:dim(lt)[1]){
        spare_genes<-as.character(lt[k,-c(1,2)])
        spare_genes[!(spare_genes %in% universe)]<- ""
        test<-spare_genes != ""
        S<-sum(test)
        if( S>= min_module_size){
          genesACSN<-unique(c(genesACSN,unique(spare_genes[test])))
          result<-rbind(result,cbind(lt[k,1],S,t(spare_genes)))          
        }
      }
      size <- length(genesACSN)
      maps[[iterator]]<-result
    }
    is_in_ACSN<-Genes %in% genesACSN
    S<-sum(!is_in_ACSN)
    if(S > 0){ ### removing genes from list, that are not from ACSN
      warning(paste(S,"genes are not in ACSN modules and will be excluded from analysis"))
    }
    Genes<-Genes[is_in_ACSN]
    
  }
  else{
    stop("Invalid universe input: must be 'HUGO','ACSN', or a gene list")
  }

  ### get from list how many are in each sub-compartment
  result<-data.frame()
  ### what would be the expected?
  for(map in maps){
    modules<-map[,1:2]
    if(statistical_test == "fisher"){
      print(head(map[,1:5]))
       p.values<-apply(map,MARGIN = 1, FUN = function(z){
         short_z<-z[z!=""][-c(1,2)] ### remove empty slots, module name and length
         num<-as.numeric(as.character(z[2]))
         Genes_in_module<-length(Genes %in% short_z)
         fisher.test(x = matrix(c(Genes_in_module,
                                  num-Genes_in_module,
                                  Genes_size - Genes_in_module,
                                  size - num),
                                  nrow = 2))$p.value
         
       })
       result<-rbind(result,cbind(modules,p.values))
    }
  }
  return(result)
}

represent_enrichment<-function(enrichment){
  
  
  
}


format_from_gmt<-function(path = ""){
  max_length<-max(sapply(X=readLines(path),FUN = function(z){
    z2<-gsub("\t","",z)
    return(nchar(z)-nchar(z2))
  }))
  gmt<-read.csv(path,header = FALSE, 
                sep = "\t",fill = TRUE,
                col.names = sapply(X = 1:max_length,
                                   FUN = function(z){
                                     paste("V",z,sep="")
                                   }))
  
  result<-t(apply(gmt,1,FUN = function(z){
    pos<-grep(pattern = "\\*",x = z)
    res<-z
    res[pos]<-""
    return(res)
  }))
  result[,2]<-apply(result[,-(1:2)], 1, FUN = function(z) sum(z!=""))
  return(result)
}
